<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="arm_base_length" value ="0.1"/>
    <xacro:property name="arm_base_width" value ="0.1"/>
    <xacro:property name="arm_base_height" value ="0.02"/>
    <xacro:property name="fore_arm_length" value ="0.3"/>
    <xacro:property name="fore_arm_radius" value ="0.02"/>
    <material name="orange">
        <color rgba="1.0 0.65 0.0 1.0"/>
    </material>

    <material name="yellow">
        <color rgba="1.0 1.0 0.0 1.0"/>
    </material>
    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <material name="orange"/>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <material name="orange"/>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:box mass="0.5" length="${2*arm_base_length}" width="${2*arm_base_width}" 
            height="${arm_base_height}" xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </link>

    <link name="fore_arm_link">
        <visual>
            <geometry>
                <cylinder radius="${fore_arm_radius}" length="${fore_arm_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${fore_arm_length/2}" rpy="0.0 0.0 0.0"/>
            <material name="yellow"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${fore_arm_radius}" length="${fore_arm_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${fore_arm_length/2}" rpy="0.0 0.0 0.0"/>
            <material name="yellow"/>
        </collision>
        <xacro:cylinder mass="0.3" radius="${2*fore_arm_radius}" height="${2*fore_arm_length}"
            xyz="0.0 0.0 ${fore_arm_length/2}" rpy="0.0 0.0 0.0"/>
    </link>

    <joint name="arm_base_fore_arm_joint" type="revolute">
        <parent link="arm_base_link"/>
        <child link="fore_arm_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-pi/2}" upper="${pi/2}" velocity="100.0" effort="100.0"/>
        <dynamics friction="0.05" damping="0.1" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="${fore_arm_radius}" length="${fore_arm_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${fore_arm_length/2}" rpy="0.0 0.0 0.0"/>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${fore_arm_radius}" length="${fore_arm_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${fore_arm_length/2}" rpy="0.0 0.0 0.0"/>
            <material name="orange"/>
        </collision>
        <xacro:cylinder mass="0.3" radius="${2*fore_arm_radius}" height="${2*fore_arm_length}"
            xyz="0.0 0.0 ${fore_arm_length/2}" rpy="0.0 0.0 0.0"/>
    </link>
    
    <joint name="fore_arm_hand_joint" type="revolute">
        <parent link="fore_arm_link"/>
        <child link="hand_link"/>
        <axis xyz="0 1 0"/>
        <limit lower="${-pi/2}" upper="${pi/2}" velocity="100.0" effort="100.0"/>
        <dynamics friction="0.05" damping="0.1" />
        <origin xyz="0 0 ${fore_arm_length}" rpy="0 0 0"/>
    </joint>
    
    
</robot>