<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="axlr_properties.urdf.xacro"/>
    <xacro:include filename="axlr_base.urdf.xacro"/>
    <xacro:include filename="axlr_arm.urdf.xacro"/>
    <xacro:include filename="axlr_camera.urdf.xacro"/>
    <xacro:include filename="axlr_gazebo.urdf.xacro"/>

    <joint name="base_link_arm_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="arm_base_link"/>
        <origin xyz="${base_length/4} 0.0 ${base_height}" rpy="0.0 0.0 0.0"/>
    </joint>
</robot>